package try_1.t12.q1;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Circle.java
//  @ Date : 2012/03/15
//  @ Author : 
//
//




public class Circle implements Inter3 {
	private double _radius;
	private double _diameter;
	public void showMessage() {
	
	}

}
