//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Circle.java
//  @ Date : 2012/03/15
//  @ Author : 
//
//



package t12.q1;


public class Circle implements Inter3 {
	private double _radius;
	private double _diameter;
	public String _color;
	public void showMessage() {
	
	}
	

}
