//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Inter3.java
//  @ Date : 2012/03/15
//  @ Author : 
//
//



package t12.q1;


public interface Inter3 {
	public abstract void showMessage();
}
