/************************************`
 * Q2_change_access_level.java
 * Author: iwabuchiken
 * Date: 2012/2012/03/16/8:25:16
 * Aim:								*
 * 	1.
 * <Usage>
 *	1. Run the program
 * <Source>
 * 	1. 
 ************************************/
/**
 * 
 */
package try_1.t14.q1;

/**
 * @author iwabuchiken
 *
 */
public class Q2_change_access_level {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO 自動生成されたメソッド・スタブ
		SubClassQ2	sub1	= new SubClassQ2();
		
		sub1.showMessage("I am an instance of SubClassQ2");
		sub1.showMessage(300);
	}

}

class SuperClassQ2 {
	public void showMessage(String message) {
		System.out.println("SuperClassQ2: showMessage(String message)");
//		System.out.println("SuperClassQ2: showMessage()");
		System.out.println("message is: " + message);
	}//showMessage()
}//class SuperClassQ2

class SubClassQ2 extends SuperClassQ2 {
//	public void showMessage(int message) {
	public void showMessage(String message) {
		System.out.println("SubClassQ2: showMessage(String message)");
//		System.out.println("SubClassQ2: showMessage()");
		System.out.println("message is: " + message);
	}//showMessage()

	/**
	 * @param i
	 */
	public void showMessage(int message) {
		// TODO 自動生成されたメソッド・スタブ
		System.out.println("SubClassQ2: showMessage(int message)");
//		System.out.println("SubClassQ2: showMessage()");
		System.out.println("message is: " + message);
	}
}//class SubClassQ2


/*
//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.cpp
//  @ Date : 2012/03/16
//  @ Author : 
//
//


#include "Main.h"

int Main::akicode_tbl_create() {

}

int Main::akicode_tbl_read() {

}


*/

/* 20120316_131925
#if !defined(_MAIN_H)
#define _MAIN_H


class Main {
public:
	int akicode_tbl;
	int codedata_tbl;
	int akicode_tbl_read();
private:
	int akicode_tbl_create();
};

#endif  //_MAIN_H
*/